// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WPPContext))]
    [Migration("20220206160459_SeedAddItemData")]
    partial class SeedAddItemData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Hybrid Work"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Hybrid Work Research"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Modern Collaboration"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Employee Experience"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Next Gen Endpoints and Devices"
                        });
                });

            modelBuilder.Entity("Domain.Format", b =>
                {
                    b.Property<int>("FormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormatId");

                    b.ToTable("Format");

                    b.HasData(
                        new
                        {
                            FormatId = 1,
                            Name = "On-demand Videos"
                        },
                        new
                        {
                            FormatId = 2,
                            Name = "Events and Webinars"
                        },
                        new
                        {
                            FormatId = 3,
                            Name = "Articles and eBooks"
                        },
                        new
                        {
                            FormatId = 4,
                            Name = "Immersion Workshops"
                        },
                        new
                        {
                            FormatId = 5,
                            Name = "Technical Training"
                        },
                        new
                        {
                            FormatId = 6,
                            Name = "End User Training"
                        });
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormatId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FormatId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1,
                            Description = "Learn about the lasting impact of remote work on collaboration work patterns.",
                            FormatId = 1,
                            Image = "",
                            Link = "",
                            Title = "The effects of remote work on collaboration among information workers"
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 2,
                            Description = "Sign up for Teams Connect to collaborate seamlessly in the same digital environment with anyone, wether inside or outside your organization.",
                            FormatId = 2,
                            Image = "",
                            Link = "",
                            Title = "Sign up for Microsoft Teams Connect"
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 3,
                            Description = "Learn how Microsoft is partnering with leading brands and retailers from across the globe on their hybrid work journeys.",
                            FormatId = 3,
                            Image = "",
                            Link = "",
                            Title = "Empowering Hybrid Work for Brands & Retailers"
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 4,
                            Description = "Learn how you can use collaborative apps to simplify and streamline business processes.",
                            FormatId = 4,
                            Image = "",
                            Link = "",
                            Title = "Digitizing hybrid Work processes"
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 5,
                            Description = "Learn more about Windows 365, see a product demo, and discover the opportunities that Cloud OC presents in the hybrid workplace.",
                            FormatId = 5,
                            Image = "",
                            Link = "",
                            Title = "Hybrid Windows for a Hybrid World"
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 1,
                            Description = "Explore the key principles behind Microsoft's approach to modern endpoints and the learn why endpoint management and compliance is essential to your Zero Trust security journey.",
                            FormatId = 6,
                            Image = "",
                            Link = "",
                            Title = "Modernizing Endpoints in the Digital Estate"
                        });
                });

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.HasOne("Domain.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Format", "Format")
                        .WithMany("Items")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Format", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
